# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_UI/Register.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CRegister(object):
    def setupUi(self, CRegister):
        CRegister.setObjectName("CRegister")
        CRegister.resize(260, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CRegister.sizePolicy().hasHeightForWidth())
        CRegister.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CRegister.setWindowIcon(icon)
        self.Label_User = QtWidgets.QLabel(CRegister)
        self.Label_User.setGeometry(QtCore.QRect(20, 40, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_User.setFont(font)
        self.Label_User.setObjectName("Label_User")
        self.Lablel_Psw1 = QtWidgets.QLabel(CRegister)
        self.Lablel_Psw1.setGeometry(QtCore.QRect(20, 75, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Lablel_Psw1.setFont(font)
        self.Lablel_Psw1.setObjectName("Lablel_Psw1")
        self.Label_Psw2 = QtWidgets.QLabel(CRegister)
        self.Label_Psw2.setGeometry(QtCore.QRect(20, 110, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_Psw2.setFont(font)
        self.Label_Psw2.setObjectName("Label_Psw2")
        self.Label_Dinner = QtWidgets.QLabel(CRegister)
        self.Label_Dinner.setGeometry(QtCore.QRect(20, 180, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_Dinner.setFont(font)
        self.Label_Dinner.setObjectName("Label_Dinner")
        self.Label_Bus = QtWidgets.QLabel(CRegister)
        self.Label_Bus.setGeometry(QtCore.QRect(20, 215, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_Bus.setFont(font)
        self.Label_Bus.setObjectName("Label_Bus")
        self.Text_User = QtWidgets.QLineEdit(CRegister)
        self.Text_User.setGeometry(QtCore.QRect(100, 40, 140, 25))
        self.Text_User.setObjectName("Text_User")
        self.Text_Psw1 = QtWidgets.QLineEdit(CRegister)
        self.Text_Psw1.setGeometry(QtCore.QRect(100, 75, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Text_Psw1.setFont(font)
        self.Text_Psw1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Text_Psw1.setObjectName("Text_Psw1")
        self.Text_Psw2 = QtWidgets.QLineEdit(CRegister)
        self.Text_Psw2.setGeometry(QtCore.QRect(100, 110, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Text_Psw2.setFont(font)
        self.Text_Psw2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Text_Psw2.setObjectName("Text_Psw2")
        self.Combo_Dinner = QtWidgets.QComboBox(CRegister)
        self.Combo_Dinner.setGeometry(QtCore.QRect(100, 180, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Combo_Dinner.setFont(font)
        self.Combo_Dinner.setObjectName("Combo_Dinner")
        self.Combo_Dinner.addItem("")
        self.Combo_Dinner.addItem("")
        self.Combo_Bus = QtWidgets.QComboBox(CRegister)
        self.Combo_Bus.setGeometry(QtCore.QRect(100, 215, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Combo_Bus.setFont(font)
        self.Combo_Bus.setObjectName("Combo_Bus")
        self.Combo_Bus.addItem("")
        self.Combo_Bus.addItem("")
        self.Text_Reason = QtWidgets.QLineEdit(CRegister)
        self.Text_Reason.setGeometry(QtCore.QRect(100, 250, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Text_Reason.setFont(font)
        self.Text_Reason.setObjectName("Text_Reason")
        self.Btn_Regist = QtWidgets.QPushButton(CRegister)
        self.Btn_Regist.setGeometry(QtCore.QRect(165, 285, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Btn_Regist.setFont(font)
        self.Btn_Regist.setObjectName("Btn_Regist")
        self.Text_RegCode = QtWidgets.QLineEdit(CRegister)
        self.Text_RegCode.setGeometry(QtCore.QRect(100, 145, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Text_RegCode.setFont(font)
        self.Text_RegCode.setObjectName("Text_RegCode")
        self.Label_RegCode = QtWidgets.QLabel(CRegister)
        self.Label_RegCode.setGeometry(QtCore.QRect(20, 145, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_RegCode.setFont(font)
        self.Label_RegCode.setObjectName("Label_RegCode")
        self.Label_Reason = QtWidgets.QLabel(CRegister)
        self.Label_Reason.setGeometry(QtCore.QRect(20, 250, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_Reason.setFont(font)
        self.Label_Reason.setObjectName("Label_Reason")
        self.Label_Status = QtWidgets.QLabel(CRegister)
        self.Label_Status.setGeometry(QtCore.QRect(20, 285, 130, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.Label_Status.setFont(font)
        self.Label_Status.setText("")
        self.Label_Status.setObjectName("Label_Status")
        self.Tool_Close = QtWidgets.QToolButton(CRegister)
        self.Tool_Close.setGeometry(QtCore.QRect(230, 0, 20, 20))
        self.Tool_Close.setText("")
        self.Tool_Close.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Tool_Close.setObjectName("Tool_Close")
        self.Tool_Min = QtWidgets.QToolButton(CRegister)
        self.Tool_Min.setGeometry(QtCore.QRect(210, 0, 20, 20))
        self.Tool_Min.setText("")
        self.Tool_Min.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.Tool_Min.setObjectName("Tool_Min")
        self.Label_Register = QtWidgets.QLabel(CRegister)
        self.Label_Register.setGeometry(QtCore.QRect(10, 0, 140, 25))
        self.Label_Register.setObjectName("Label_Register")

        self.retranslateUi(CRegister)
        QtCore.QMetaObject.connectSlotsByName(CRegister)
        CRegister.setTabOrder(self.Text_User, self.Text_Psw1)
        CRegister.setTabOrder(self.Text_Psw1, self.Text_Psw2)
        CRegister.setTabOrder(self.Text_Psw2, self.Text_RegCode)
        CRegister.setTabOrder(self.Text_RegCode, self.Combo_Dinner)
        CRegister.setTabOrder(self.Combo_Dinner, self.Combo_Bus)
        CRegister.setTabOrder(self.Combo_Bus, self.Text_Reason)
        CRegister.setTabOrder(self.Text_Reason, self.Btn_Regist)

    def retranslateUi(self, CRegister):
        _translate = QtCore.QCoreApplication.translate
        CRegister.setWindowTitle(_translate("CRegister", "注册"))
        self.Label_User.setText(_translate("CRegister", "用户名："))
        self.Lablel_Psw1.setText(_translate("CRegister", "密码："))
        self.Label_Psw2.setText(_translate("CRegister", "确认密码："))
        self.Label_Dinner.setText(_translate("CRegister", "加班餐："))
        self.Label_Bus.setText(_translate("CRegister", "加班班车："))
        self.Combo_Dinner.setItemText(0, _translate("CRegister", "是"))
        self.Combo_Dinner.setItemText(1, _translate("CRegister", "否"))
        self.Combo_Bus.setItemText(0, _translate("CRegister", "是"))
        self.Combo_Bus.setItemText(1, _translate("CRegister", "否"))
        self.Text_Reason.setText(_translate("CRegister", "加班"))
        self.Btn_Regist.setText(_translate("CRegister", "注册"))
        self.Label_RegCode.setText(_translate("CRegister", "注册码："))
        self.Label_Reason.setText(_translate("CRegister", "加班理由："))
        self.Label_Register.setText(_translate("CRegister", "欢迎使用一键加班系统！"))

